artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_url: "C:\Users\realme\Documents\Downloads\archive (20).zip"
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion 

